#!/usr/bin/env fish

set todo_location $HOME/.todo
set todo_txt todo.txt
source $HOME/.config/todo/config
set todo $todo_location/$todo_txt
set PAGER bat

function usage
	echo "Usage: todo [OPERATION]"
	echo ""
	echo "Help Options:"
	echo "	-h, --help		Show help options"
	echo ""
	echo "Operations:"
	echo "	l, ls, list		Show contents of todo.txt"
	echo "	e, edit, \$EDITOR	Edit contents of todo.txt"
	echo "	a, add			Add task item to todo.txt"
	exit 0
end

if test -z $argv[1]
	usage
	exit 0
else if test $argv[1] = "l"; or test $argv[1] = "ls"; or test $argv[1] = "list"
	$PAGER "$todo"
	exit 0
else if test $argv[1] = "e"; or test $argv[1] = "edit"; or test $argv[1] = "$EDITOR"
	$EDITOR "$todo"
	$PAGER "$todo"
	exit 0
else if test $argv[1] = "a"; or test $argv[1] = "add"
	if test -z $argv[2]
		echo "todo: task not inputted"
		exit 1
	end
	echo $argv[2..(count $argv)] >> $todo
	$PAGER "$todo"
	exit 0
end

usage
